/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_puppy_puppymouseinput_OpenCVNativeMethods */

#ifndef _Included_com_puppy_puppymouseinput_OpenCVNativeMethods
#define _Included_com_puppy_puppymouseinput_OpenCVNativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_puppy_puppymouseinput_OpenCVNativeMethods
 * Method:    YUVData2OpenCV
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_com_puppy_puppymouseinput_OpenCVNativeMethods_YUVData2OpenCV
  (JNIEnv *env, jobject obj, jint height, jint width, jbyteArray previewYuv){

}

#ifdef __cplusplus
}
#endif
#endif
